default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: bookstore_development

test:
  <<: *default
  database: bookstore_test
  host: <%= ENV['POSTGRES_HOST'] || 'db' %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>

production:
  <<: *default
  database: bookstore
