FROM ruby:3.4.5

RUN apt-get update -qq && apt-get install -y curl build-essential libpq-dev

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

COPY entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh

EXPOSE 3000

CMD ["sh", "/usr/bin/entrypoint.sh"]