services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - ruby_gems:/usr/local/bundle
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
volumes:
  postgres:
  ruby_gems:
