services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - ruby_gems:/usr/local/bundle
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
  ruby_gems:
