services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: entrypoint.sh
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
